### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Red-King-Sureiya** [ywssp/Bot.wssp#7]
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
at PlayCommand.exec (/app/commands/Music/play.js:218:50)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at async CommandHandler.runCommand (/rbd/pnpm-volume/4b636467-7917-4746-a8d0-5d3f18a442eb/node_modules/.registry.npmjs.org/discord-akairo/8.0.0/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:755:25)
    at async CommandHandler.handleDirectCommand (/rbd/pnpm-volume/4b636467-7917-4746-a8d0-5d3f18a442eb/node_modules/.registry.npmjs.org/discord-akairo/8.0.0/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:437:20)
    at async CommandHandler.handle (/rbd/pnpm-volume/4b636467-7917-4746-a8d0-5d3f18a442eb/node_modules/.registry.npmjs.org/discord-akairo/8.0.0/node_modules/discord-akairo/src/struct/commands/CommandHandler.js:377:23)
(node:25500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ywssp** [comment]
The code is now fixed, i just made a typo when making an array😅

The part where the error occured:
```
[('1️⃣', '2️⃣', '3️⃣', '4️⃣', '5️⃣', '🛑')].forEach(
      async (emoji) => await songEmbed.react(emoji)
    );```

**Comment by Red-King-Sureiya** [comment]
Oh thank you for the quick response and i just tried the bot the queue is not responding if there is 2 more songs in queue
